### ISSUE TITLE
Extract the email script from Time/API

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/hapi-email#11]
We have "*solved*" this problem:
https://github.com/dwyl/time/blob/81a96d93af5a69755e89fe38a7e70e2560f75988/api/lib/email_welcome.js we need to make it generic.

**Comment by nelsonic** [comment]
This is done. We will *soon* be able to re-do Time with a fully *modular* build. :open_mouth:

**Comment by iteles** [comment]
😱🙌🏻
