### ISSUE TITLE
Quick question, thought you might know.

### ISSUE THREAD

**Issue by trusktr** [nelsonic/hapi-email#6]
Can we send emails from something we've deployed to `<subdomain>.meteor.com`?

**Comment by nelsonic** [comment]
Hi @trusktr, apologies for the delayed reply, we are no longer supporting Meteor, we are building an *tested*, *accessible*, *reliable*, *scalable* stack based on http://hapijs.com we *encourage* you to explore it!
see: https://github.com/nelsonic/learn-hapi
If you still need help with anything Meteor-related, please speak to: https://twitter.com/meteorlondon
