### ISSUE TITLE
Meteor release 

### ISSUE THREAD

**Issue by Shekharrajak** [nelsonic/hapi-email#7]
This project says that it uses Meteor 0.7.1.2, but you don't have that
version of Meteor installed and the Meteor update servers don't have it
either. Please edit the .meteor/release file in the project and change it
to a valid Meteor release.

How can I fix this problem?
We can't update to current new version1.1.0.2 through terminal.

Is there any way to do this?

**Comment by nelsonic** [comment]
@Shekharrajak thanks for getting in touch. we are no longer using Meteor. If you want to submit a Pull Request to update the code, please do. thanks. :+1:

**Comment by Shekharrajak** [comment]
Yeah I am trying to fix this.
How much time it  takes to send mail ?

**Comment by nelsonic** [comment]
It should not take more than a minute for GMail to send an email. it usually takes only a couple of seconds.

**Comment by Shekharrajak** [comment]
The app is running but I don't know why I am not receiving the email, for the verification link.

**Comment by nelsonic** [comment]
@Shekharrajak we are no longer supporting Meteor, we are building an *tested*, *accessible*, *reliable*, *scalable* stack based on http://hapijs.com we *encourage* you to explore it!
see: https://github.com/nelsonic/learn-hapi
If you still need help with anything Meteor-related, please speak to: https://twitter.com/meteorlondon
